/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Terminal: typeof import('primevue/terminal')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
